/*
 * This source file was generated by the Gradle 'init' task
 */
package helloworkflow;

public class Starter {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Starter().getGreeting());
    }
}
